# Generated by Django 3.1 on 2020-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Route name')),
                ('from_city', models.CharField(max_length=100, verbose_name='From')),
                ('to_city', models.CharField(max_length=100, verbose_name='To')),
                ('travel_times', models.IntegerField(verbose_name='Duration')),
                ('across_cities', models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Through cities')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['name'],
            },
        ),
    ]
